// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetReleases() {
  return window['go']['main']['App']['GetReleases']();
}

export function InstallRelease(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallRelease'](arg1, arg2, arg3);
}

export function OpenInstallationFolder() {
  return window['go']['main']['App']['OpenInstallationFolder']();
}

export function OpenURL(arg1) {
  return window['go']['main']['App']['OpenURL'](arg1);
}

export function UninstallRelease(arg1) {
  return window['go']['main']['App']['UninstallRelease'](arg1);
}
