// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetReleases():Promise<Array<main.ProtonRelease>>;

export function InstallRelease(arg1:string,arg2:string,arg3:number):Promise<void>;

export function OpenInstallationFolder():Promise<void>;

export function OpenURL(arg1:string):Promise<void>;

export function UninstallRelease(arg1:string):Promise<void>;
