name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**' # Dispara apenas se houver alterações na pasta web
      - 'portfolio-assets/**' # Adicionado para disparar quando os assets mudarem
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout do Código
        uses: actions/checkout@v4

      - name: 🏗️ Compor Pasta de Documentação
        run: |
          # Garante que o destino existe e copia os assets para dentro de docs/portfolio-assets
          mkdir -p ./docs/assets
          cp -R ./portfolio-assets/* ./docs/assets/

      - name: ⚙️ Configurar Pages
        uses: actions/configure-pages@v5

      - name: 📦 Upload do Artefato (Docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: 🚀 Deploy para GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4